/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface CoOwnableInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "primaryOwner"
      | "secondaryOwner"
      | "transferPrimaryOwnership"
      | "transferSecondaryOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PrimaryOwnershipTransferred"
      | "SecondaryOwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "primaryOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "secondaryOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferPrimaryOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferSecondaryOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "primaryOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "secondaryOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferPrimaryOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferSecondaryOwnership",
    data: BytesLike
  ): Result;
}

export namespace PrimaryOwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SecondaryOwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CoOwnable extends BaseContract {
  connect(runner?: ContractRunner | null): CoOwnable;
  waitForDeployment(): Promise<this>;

  interface: CoOwnableInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  primaryOwner: TypedContractMethod<[], [string], "view">;

  secondaryOwner: TypedContractMethod<[], [string], "view">;

  transferPrimaryOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  transferSecondaryOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "primaryOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "secondaryOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferPrimaryOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferSecondaryOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "PrimaryOwnershipTransferred"
  ): TypedContractEvent<
    PrimaryOwnershipTransferredEvent.InputTuple,
    PrimaryOwnershipTransferredEvent.OutputTuple,
    PrimaryOwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SecondaryOwnershipTransferred"
  ): TypedContractEvent<
    SecondaryOwnershipTransferredEvent.InputTuple,
    SecondaryOwnershipTransferredEvent.OutputTuple,
    SecondaryOwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "PrimaryOwnershipTransferred(address,address)": TypedContractEvent<
      PrimaryOwnershipTransferredEvent.InputTuple,
      PrimaryOwnershipTransferredEvent.OutputTuple,
      PrimaryOwnershipTransferredEvent.OutputObject
    >;
    PrimaryOwnershipTransferred: TypedContractEvent<
      PrimaryOwnershipTransferredEvent.InputTuple,
      PrimaryOwnershipTransferredEvent.OutputTuple,
      PrimaryOwnershipTransferredEvent.OutputObject
    >;

    "SecondaryOwnershipTransferred(address,address)": TypedContractEvent<
      SecondaryOwnershipTransferredEvent.InputTuple,
      SecondaryOwnershipTransferredEvent.OutputTuple,
      SecondaryOwnershipTransferredEvent.OutputObject
    >;
    SecondaryOwnershipTransferred: TypedContractEvent<
      SecondaryOwnershipTransferredEvent.InputTuple,
      SecondaryOwnershipTransferredEvent.OutputTuple,
      SecondaryOwnershipTransferredEvent.OutputObject
    >;
  };
}
