/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SwapRouterRestricted } from "./SwapRouterRestricted";
export * as factories from "./factories";
export { SwapRouterRestricted__factory } from "./factories/SwapRouterRestricted__factory";
