/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IDexInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addProvider"
      | "changePairState"
      | "closeOrder"
      | "collectFees"
      | "depositLiquidity"
      | "getNewPairParams"
      | "getPair"
      | "newPair"
      | "orderMaxTimeout"
      | "priceManager"
      | "removeProvider"
      | "setOrderMaxTimeout"
      | "setPriceManager"
      | "submitOrder"
      | "withdrawLiquidity"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "NewMaxTimeout" | "NewPair" | "NewPairState"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addProvider",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changePairState",
    values: [AddressLike, AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "closeOrder",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collectFees",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositLiquidity",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNewPairParams",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPair",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "newPair",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "orderMaxTimeout",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "priceManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeProvider",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOrderMaxTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitOrder",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawLiquidity",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changePairState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "closeOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collectFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNewPairParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPair", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "newPair", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "orderMaxTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "priceManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOrderMaxTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPriceManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawLiquidity",
    data: BytesLike
  ): Result;
}

export namespace NewMaxTimeoutEvent {
  export type InputTuple = [timeout: BigNumberish];
  export type OutputTuple = [timeout: bigint];
  export interface OutputObject {
    timeout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewPairEvent {
  export type InputTuple = [
    token0: AddressLike,
    token1: AddressLike,
    pair: AddressLike
  ];
  export type OutputTuple = [token0: string, token1: string, pair: string];
  export interface OutputObject {
    token0: string;
    token1: string;
    pair: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewPairStateEvent {
  export type InputTuple = [pair: AddressLike, isActive: boolean];
  export type OutputTuple = [pair: string, isActive: boolean];
  export interface OutputObject {
    pair: string;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IDex extends BaseContract {
  connect(runner?: ContractRunner | null): IDex;
  waitForDeployment(): Promise<this>;

  interface: IDexInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addProvider: TypedContractMethod<
    [
      token0: AddressLike,
      token1: AddressLike,
      provider: AddressLike,
      allowedMaxBalance0: BigNumberish,
      allowedMaxBalance1: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  changePairState: TypedContractMethod<
    [token0: AddressLike, token1: AddressLike, state: boolean],
    [void],
    "nonpayable"
  >;

  closeOrder: TypedContractMethod<
    [token0: AddressLike, token1: AddressLike, id: BigNumberish],
    [void],
    "nonpayable"
  >;

  collectFees: TypedContractMethod<
    [token0: AddressLike, token1: AddressLike],
    [void],
    "nonpayable"
  >;

  depositLiquidity: TypedContractMethod<
    [
      token0: AddressLike,
      token1: AddressLike,
      amount0: BigNumberish,
      amount1: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getNewPairParams: TypedContractMethod<
    [],
    [
      [string, string, bigint] & { token0: string; token1: string; fee: bigint }
    ],
    "view"
  >;

  getPair: TypedContractMethod<
    [token0: AddressLike, token1: AddressLike],
    [string],
    "view"
  >;

  newPair: TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike, fee: BigNumberish],
    [string],
    "nonpayable"
  >;

  orderMaxTimeout: TypedContractMethod<[], [bigint], "view">;

  priceManager: TypedContractMethod<[], [string], "view">;

  removeProvider: TypedContractMethod<
    [token0: AddressLike, token1: AddressLike, provider: AddressLike],
    [void],
    "nonpayable"
  >;

  setOrderMaxTimeout: TypedContractMethod<
    [timeout: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPriceManager: TypedContractMethod<
    [newPriceManager: AddressLike],
    [void],
    "nonpayable"
  >;

  submitOrder: TypedContractMethod<
    [
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      timeout: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  withdrawLiquidity: TypedContractMethod<
    [
      token0: AddressLike,
      token1: AddressLike,
      amount0: BigNumberish,
      amount1: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addProvider"
  ): TypedContractMethod<
    [
      token0: AddressLike,
      token1: AddressLike,
      provider: AddressLike,
      allowedMaxBalance0: BigNumberish,
      allowedMaxBalance1: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "changePairState"
  ): TypedContractMethod<
    [token0: AddressLike, token1: AddressLike, state: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "closeOrder"
  ): TypedContractMethod<
    [token0: AddressLike, token1: AddressLike, id: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "collectFees"
  ): TypedContractMethod<
    [token0: AddressLike, token1: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositLiquidity"
  ): TypedContractMethod<
    [
      token0: AddressLike,
      token1: AddressLike,
      amount0: BigNumberish,
      amount1: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getNewPairParams"
  ): TypedContractMethod<
    [],
    [
      [string, string, bigint] & { token0: string; token1: string; fee: bigint }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPair"
  ): TypedContractMethod<
    [token0: AddressLike, token1: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "newPair"
  ): TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike, fee: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "orderMaxTimeout"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "priceManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeProvider"
  ): TypedContractMethod<
    [token0: AddressLike, token1: AddressLike, provider: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOrderMaxTimeout"
  ): TypedContractMethod<[timeout: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPriceManager"
  ): TypedContractMethod<[newPriceManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitOrder"
  ): TypedContractMethod<
    [
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      timeout: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawLiquidity"
  ): TypedContractMethod<
    [
      token0: AddressLike,
      token1: AddressLike,
      amount0: BigNumberish,
      amount1: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "NewMaxTimeout"
  ): TypedContractEvent<
    NewMaxTimeoutEvent.InputTuple,
    NewMaxTimeoutEvent.OutputTuple,
    NewMaxTimeoutEvent.OutputObject
  >;
  getEvent(
    key: "NewPair"
  ): TypedContractEvent<
    NewPairEvent.InputTuple,
    NewPairEvent.OutputTuple,
    NewPairEvent.OutputObject
  >;
  getEvent(
    key: "NewPairState"
  ): TypedContractEvent<
    NewPairStateEvent.InputTuple,
    NewPairStateEvent.OutputTuple,
    NewPairStateEvent.OutputObject
  >;

  filters: {
    "NewMaxTimeout(uint256)": TypedContractEvent<
      NewMaxTimeoutEvent.InputTuple,
      NewMaxTimeoutEvent.OutputTuple,
      NewMaxTimeoutEvent.OutputObject
    >;
    NewMaxTimeout: TypedContractEvent<
      NewMaxTimeoutEvent.InputTuple,
      NewMaxTimeoutEvent.OutputTuple,
      NewMaxTimeoutEvent.OutputObject
    >;

    "NewPair(address,address,address)": TypedContractEvent<
      NewPairEvent.InputTuple,
      NewPairEvent.OutputTuple,
      NewPairEvent.OutputObject
    >;
    NewPair: TypedContractEvent<
      NewPairEvent.InputTuple,
      NewPairEvent.OutputTuple,
      NewPairEvent.OutputObject
    >;

    "NewPairState(address,bool)": TypedContractEvent<
      NewPairStateEvent.InputTuple,
      NewPairStateEvent.OutputTuple,
      NewPairStateEvent.OutputObject
    >;
    NewPairState: TypedContractEvent<
      NewPairStateEvent.InputTuple,
      NewPairStateEvent.OutputTuple,
      NewPairStateEvent.OutputObject
    >;
  };
}
