/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IPairFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "changePairState"
      | "deployPair"
      | "getAllPairs"
      | "getPair"
      | "getPairParams"
      | "getPeripheryContracts"
      | "setPeripheryContracts"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "NewPair" | "NewPairState"): EventFragment;

  encodeFunctionData(
    functionFragment: "changePairState",
    values: [AddressLike, AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "deployPair",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllPairs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPair",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPairParams",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPeripheryContracts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPeripheryContracts",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "changePairState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deployPair", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllPairs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPair", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPairParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPeripheryContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPeripheryContracts",
    data: BytesLike
  ): Result;
}

export namespace NewPairEvent {
  export type InputTuple = [
    token0: AddressLike,
    token1: AddressLike,
    pair: AddressLike
  ];
  export type OutputTuple = [token0: string, token1: string, pair: string];
  export interface OutputObject {
    token0: string;
    token1: string;
    pair: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewPairStateEvent {
  export type InputTuple = [pair: AddressLike, isActive: boolean];
  export type OutputTuple = [pair: string, isActive: boolean];
  export interface OutputObject {
    pair: string;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPairFactory extends BaseContract {
  connect(runner?: ContractRunner | null): IPairFactory;
  waitForDeployment(): Promise<this>;

  interface: IPairFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  changePairState: TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike, state: boolean],
    [void],
    "nonpayable"
  >;

  deployPair: TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike, fee: BigNumberish],
    [string],
    "nonpayable"
  >;

  getAllPairs: TypedContractMethod<[], [string[]], "view">;

  getPair: TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike],
    [string],
    "view"
  >;

  getPairParams: TypedContractMethod<
    [],
    [
      [string, string, bigint] & { token0: string; token1: string; fee: bigint }
    ],
    "view"
  >;

  getPeripheryContracts: TypedContractMethod<
    [],
    [
      [string, string, string] & {
        priceManager: string;
        liquidityManager: string;
        orderRouter: string;
      }
    ],
    "view"
  >;

  setPeripheryContracts: TypedContractMethod<
    [
      newPriceManager: AddressLike,
      newOrderRouter: AddressLike,
      newLiquidityManager: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "changePairState"
  ): TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike, state: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deployPair"
  ): TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike, fee: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllPairs"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPair"
  ): TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPairParams"
  ): TypedContractMethod<
    [],
    [
      [string, string, bigint] & { token0: string; token1: string; fee: bigint }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPeripheryContracts"
  ): TypedContractMethod<
    [],
    [
      [string, string, string] & {
        priceManager: string;
        liquidityManager: string;
        orderRouter: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setPeripheryContracts"
  ): TypedContractMethod<
    [
      newPriceManager: AddressLike,
      newOrderRouter: AddressLike,
      newLiquidityManager: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "NewPair"
  ): TypedContractEvent<
    NewPairEvent.InputTuple,
    NewPairEvent.OutputTuple,
    NewPairEvent.OutputObject
  >;
  getEvent(
    key: "NewPairState"
  ): TypedContractEvent<
    NewPairStateEvent.InputTuple,
    NewPairStateEvent.OutputTuple,
    NewPairStateEvent.OutputObject
  >;

  filters: {
    "NewPair(address,address,address)": TypedContractEvent<
      NewPairEvent.InputTuple,
      NewPairEvent.OutputTuple,
      NewPairEvent.OutputObject
    >;
    NewPair: TypedContractEvent<
      NewPairEvent.InputTuple,
      NewPairEvent.OutputTuple,
      NewPairEvent.OutputObject
    >;

    "NewPairState(address,bool)": TypedContractEvent<
      NewPairStateEvent.InputTuple,
      NewPairStateEvent.OutputTuple,
      NewPairStateEvent.OutputObject
    >;
    NewPairState: TypedContractEvent<
      NewPairStateEvent.InputTuple,
      NewPairStateEvent.OutputTuple,
      NewPairStateEvent.OutputObject
    >;
  };
}
