/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IOrderRouter {
  export type CloseOrderParamsStruct = {
    tokenA: AddressLike;
    tokenB: AddressLike;
    id: BigNumberish;
  };

  export type CloseOrderParamsStructOutput = [
    tokenA: string,
    tokenB: string,
    id: bigint
  ] & { tokenA: string; tokenB: string; id: bigint };

  export type SubmitOrderParamsStruct = {
    owner: AddressLike;
    tokenIn: AddressLike;
    tokenOut: AddressLike;
    amountIn: BigNumberish;
    timeout: BigNumberish;
  };

  export type SubmitOrderParamsStructOutput = [
    owner: string,
    tokenIn: string,
    tokenOut: string,
    amountIn: bigint,
    timeout: bigint
  ] & {
    owner: string;
    tokenIn: string;
    tokenOut: string;
    amountIn: bigint;
    timeout: bigint;
  };
}

export declare namespace IUniswapRouter {
  export type ExactInputParamsStruct = {
    path: BytesLike;
    recipient: AddressLike;
    deadline: BigNumberish;
    amountIn: BigNumberish;
    amountOutMinimum: BigNumberish;
  };

  export type ExactInputParamsStructOutput = [
    path: string,
    recipient: string,
    deadline: bigint,
    amountIn: bigint,
    amountOutMinimum: bigint
  ] & {
    path: string;
    recipient: string;
    deadline: bigint;
    amountIn: bigint;
    amountOutMinimum: bigint;
  };

  export type ExactInputSingleParamsStruct = {
    tokenIn: AddressLike;
    tokenOut: AddressLike;
    fee: BigNumberish;
    recipient: AddressLike;
    deadline: BigNumberish;
    amountIn: BigNumberish;
    amountOutMinimum: BigNumberish;
    sqrtPriceLimitX96: BigNumberish;
  };

  export type ExactInputSingleParamsStructOutput = [
    tokenIn: string,
    tokenOut: string,
    fee: bigint,
    recipient: string,
    deadline: bigint,
    amountIn: bigint,
    amountOutMinimum: bigint,
    sqrtPriceLimitX96: bigint
  ] & {
    tokenIn: string;
    tokenOut: string;
    fee: bigint;
    recipient: string;
    deadline: bigint;
    amountIn: bigint;
    amountOutMinimum: bigint;
    sqrtPriceLimitX96: bigint;
  };

  export type ExactOutputParamsStruct = {
    path: BytesLike;
    recipient: AddressLike;
    deadline: BigNumberish;
    amountOut: BigNumberish;
    amountInMaximum: BigNumberish;
  };

  export type ExactOutputParamsStructOutput = [
    path: string,
    recipient: string,
    deadline: bigint,
    amountOut: bigint,
    amountInMaximum: bigint
  ] & {
    path: string;
    recipient: string;
    deadline: bigint;
    amountOut: bigint;
    amountInMaximum: bigint;
  };

  export type ExactOutputSingleParamsStruct = {
    tokenIn: AddressLike;
    tokenOut: AddressLike;
    fee: BigNumberish;
    recipient: AddressLike;
    deadline: BigNumberish;
    amountOut: BigNumberish;
    amountInMaximum: BigNumberish;
    sqrtPriceLimitX96: BigNumberish;
  };

  export type ExactOutputSingleParamsStructOutput = [
    tokenIn: string,
    tokenOut: string,
    fee: bigint,
    recipient: string,
    deadline: bigint,
    amountOut: bigint,
    amountInMaximum: bigint,
    sqrtPriceLimitX96: bigint
  ] & {
    tokenIn: string;
    tokenOut: string;
    fee: bigint;
    recipient: string;
    deadline: bigint;
    amountOut: bigint;
    amountInMaximum: bigint;
    sqrtPriceLimitX96: bigint;
  };
}

export interface ISwapConnectorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "closeOrder"
      | "exactInput"
      | "exactInputSingle"
      | "exactOutput"
      | "exactOutputSingle"
      | "setRouterState"
      | "submitOrder"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "NewOrderMaxTimeout"): EventFragment;

  encodeFunctionData(
    functionFragment: "closeOrder",
    values: [IOrderRouter.CloseOrderParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "exactInput",
    values: [IUniswapRouter.ExactInputParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "exactInputSingle",
    values: [IUniswapRouter.ExactInputSingleParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "exactOutput",
    values: [IUniswapRouter.ExactOutputParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "exactOutputSingle",
    values: [IUniswapRouter.ExactOutputSingleParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setRouterState",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "submitOrder",
    values: [IOrderRouter.SubmitOrderParamsStruct]
  ): string;

  decodeFunctionResult(functionFragment: "closeOrder", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "exactInput", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "exactInputSingle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "exactOutput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "exactOutputSingle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRouterState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitOrder",
    data: BytesLike
  ): Result;
}

export namespace NewOrderMaxTimeoutEvent {
  export type InputTuple = [timeout: BigNumberish];
  export type OutputTuple = [timeout: bigint];
  export interface OutputObject {
    timeout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ISwapConnector extends BaseContract {
  connect(runner?: ContractRunner | null): ISwapConnector;
  waitForDeployment(): Promise<this>;

  interface: ISwapConnectorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  closeOrder: TypedContractMethod<
    [params: IOrderRouter.CloseOrderParamsStruct],
    [void],
    "nonpayable"
  >;

  exactInput: TypedContractMethod<
    [params: IUniswapRouter.ExactInputParamsStruct],
    [bigint],
    "payable"
  >;

  exactInputSingle: TypedContractMethod<
    [params: IUniswapRouter.ExactInputSingleParamsStruct],
    [bigint],
    "payable"
  >;

  exactOutput: TypedContractMethod<
    [params: IUniswapRouter.ExactOutputParamsStruct],
    [bigint],
    "payable"
  >;

  exactOutputSingle: TypedContractMethod<
    [params: IUniswapRouter.ExactOutputSingleParamsStruct],
    [bigint],
    "payable"
  >;

  setRouterState: TypedContractMethod<
    [router: AddressLike, state: boolean],
    [void],
    "nonpayable"
  >;

  submitOrder: TypedContractMethod<
    [params: IOrderRouter.SubmitOrderParamsStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "closeOrder"
  ): TypedContractMethod<
    [params: IOrderRouter.CloseOrderParamsStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "exactInput"
  ): TypedContractMethod<
    [params: IUniswapRouter.ExactInputParamsStruct],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "exactInputSingle"
  ): TypedContractMethod<
    [params: IUniswapRouter.ExactInputSingleParamsStruct],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "exactOutput"
  ): TypedContractMethod<
    [params: IUniswapRouter.ExactOutputParamsStruct],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "exactOutputSingle"
  ): TypedContractMethod<
    [params: IUniswapRouter.ExactOutputSingleParamsStruct],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "setRouterState"
  ): TypedContractMethod<
    [router: AddressLike, state: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitOrder"
  ): TypedContractMethod<
    [params: IOrderRouter.SubmitOrderParamsStruct],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "NewOrderMaxTimeout"
  ): TypedContractEvent<
    NewOrderMaxTimeoutEvent.InputTuple,
    NewOrderMaxTimeoutEvent.OutputTuple,
    NewOrderMaxTimeoutEvent.OutputObject
  >;

  filters: {
    "NewOrderMaxTimeout(uint256)": TypedContractEvent<
      NewOrderMaxTimeoutEvent.InputTuple,
      NewOrderMaxTimeoutEvent.OutputTuple,
      NewOrderMaxTimeoutEvent.OutputObject
    >;
    NewOrderMaxTimeout: TypedContractEvent<
      NewOrderMaxTimeoutEvent.InputTuple,
      NewOrderMaxTimeoutEvent.OutputTuple,
      NewOrderMaxTimeoutEvent.OutputObject
    >;
  };
}
