/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPriceManager,
  IPriceManagerInterface,
} from "../../../contracts/interfaces/IPriceManager";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "token0",
            type: "address",
          },
          {
            internalType: "address",
            name: "token1",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "price",
            type: "uint256",
          },
        ],
        internalType: "struct IPriceManager.Price[]",
        name: "prices",
        type: "tuple[]",
      },
    ],
    name: "updatePrices",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPriceManager__factory {
  static readonly abi = _abi;
  static createInterface(): IPriceManagerInterface {
    return new Interface(_abi) as IPriceManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPriceManager {
    return new Contract(address, _abi, runner) as unknown as IPriceManager;
  }
}
